flask_app:
  replicas: 2
  image: flask-app
  imagePullPolicy: Never
  port: 8082
  host: localhost
  path: /

  resources:
    requests:
      memory: 64Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
  
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%

##########################################
mysql:
  image: mysql:5.6
  storage: 5Gi
  password: test1234
  deploymentStrategy: Recreate

  resources:
    requests:
      memory: 256Mi
      cpu: 1
    limits:
      memory: 2Gi
      cpu: 2
